# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecondblog', '0005_auto_20180122_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_deep_learning',
            name='main_content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='article_net',
            name='main_content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='article_personal',
            name='main_content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='article_python',
            name='main_content',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article_deep_learning',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_net',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_personal',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article_python',
            name='content',
            field=models.TextField(),
        ),
    ]
