# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysecondblog', '0006_auto_20180214_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_personal',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploadImage', verbose_name='PHOTO'),
            preserve_default=False,
        ),
    ]
