# Generated by Django 2.1.7 on 2019-02-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysecondblog', '0008_auto_20180301_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('main_content', models.CharField(default='', max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='uploadImage', verbose_name='PHOTO')),
            ],
        ),
        migrations.DeleteModel(
            name='Article_deep_learning',
        ),
        migrations.DeleteModel(
            name='Article_net',
        ),
        migrations.DeleteModel(
            name='Article_personal',
        ),
        migrations.DeleteModel(
            name='Article_python',
        ),
    ]
